

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (1, 'Aloisia', 'Jakoviljevic', 681);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (2, 'Cilka', 'Pannaman', 512);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (3, 'Johnathon', 'Cosgreave', 133);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (4, 'Andris', 'Deniscke', 208);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (5, 'Franciskus', 'Matteoni', 831);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (6, 'Shannon', 'Rapley', 470);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (7, 'Abbott', 'Alwell', 341);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (8, 'Lauren', 'Ortmann', 280);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (9, 'Hubey', 'Nisby', 314);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (10, 'Burr', 'Baford', 634);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (11, 'Hammad', 'Bossingham', 658);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (12, 'Trixy', 'Scamel', 248);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (13, 'Flora', 'Chatters', 17);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (14, 'Ring', 'Gamell', 93);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (15, 'Harland', 'Reiner', 93);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (16, 'Phil', 'Rosenbusch', 87);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (17, 'Lela', 'Santello', 153);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (18, 'Ema', 'Mebs', 401);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (19, 'Agnola', 'Shorton', 368);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (20, 'Marlow', 'Konrad', 530);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (21, 'Agna', 'Abley', 128);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (22, 'Rosemonde', 'Puckinghorne', 837);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (23, 'Lutero', 'Marklew', 999);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (24, 'Darill', 'Sivill', 428);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (25, 'Georgeanna', 'Cavozzi', 165);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (26, 'Daisi', 'Jarlmann', 781);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (27, 'Jocelyne', 'Todeo', 183);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (28, 'Kristy', 'Eytel', 774);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (29, 'Ronica', 'Ranscome', 78);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (30, 'Janos', 'McDougal', 63);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (31, 'Berni', 'Gantlett', 422);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (32, 'Alanah', 'Bignold', 789);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (33, 'Tann', 'Biddle', 683);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (34, 'Karine', 'Loveitt', 468);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (35, 'Cynthia', 'Francescone', 517);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (36, 'Efren', 'Magovern', 347);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (37, 'Jeannette', 'Beecraft', 496);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (38, 'Dagny', 'Kinder', 399);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (39, 'Jannelle', 'Jeandet', 408);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (40, 'Britte', 'Sandwick', 645);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (41, 'Simonette', 'MacLennan', 509);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (42, 'Madeleine', 'Cheesley', 506);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (43, 'Mile', 'Marvel', 453);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (44, 'Brinna', 'Gallone', 511);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (45, 'Coreen', 'Welbourn', 974);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (46, 'Lethia', 'Paine', 601);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (47, 'Salomo', 'Bernier', 738);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (48, 'Husain', 'Dunan', 749);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (49, 'Fay', 'Mesnard', 432);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (50, 'Georgiana', 'Mullinger', 208);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (51, 'Anitra', 'Sellar', 89);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (52, 'Cele', 'Bacon', 137);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (53, 'Reinhard', 'Bowdon', 464);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (54, 'Napoleon', 'Pirrey', 502);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (55, 'Richardo', 'Petrak', 47);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (56, 'Axe', 'Keerl', 892);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (57, 'Hillie', 'Brindley', 884);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (58, 'Ofella', 'Hartnup', 44);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (59, 'Tait', 'McEvilly', 200);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (60, 'Ania', 'Phipps', 461);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (61, 'Jada', 'Caldow', 898);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (62, 'Bennett', 'Oldfield-Cherry', 526);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (63, 'Rolph', 'Warboys', 408);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (64, 'Tressa', 'Swatton', 952);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (65, 'Auberta', 'Puleston', 843);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (66, 'Mabel', 'Ismail', 419);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (67, 'Stephanus', 'Charle', 255);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (68, 'Clair', 'Mugg', 478);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (69, 'Torin', 'Bullers', 286);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (70, 'Pooh', 'Lymer', 678);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (71, 'Judye', 'Babcock', 384);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (72, 'Giffie', 'Durward', 798);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (73, 'Agneta', 'Dobbins', 637);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (74, 'Elvis', 'Swetmore', 715);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (75, 'Hilary', 'Deval', 403);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (76, 'Karita', 'Jahner', 760);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (77, 'Mateo', 'Pettie', 509);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (78, 'Gale', 'Kilshaw', 642);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (79, 'Klemens', 'Hanaby', 326);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (80, 'Carley', 'Bawcock', 299);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (81, 'Grier', 'Gittoes', 979);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (82, 'Henrieta', 'Kubu', 220);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (83, 'Joscelin', 'Raikes', 608);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (84, 'Raquela', 'Kleisel', 656);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (85, 'Ellene', 'Molloy', 742);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (86, 'Gilburt', 'Snel', 280);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (87, 'Mamie', 'Haggeth', 865);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (88, 'Mayor', 'Licas', 530);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (89, 'Willy', 'Purdie', 894);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (90, 'Sharron', 'Hegarty', 159);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (91, 'Marie-ann', 'Tremayne', 228);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (92, 'Tybi', 'Matejka', 56);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (93, 'Grata', 'Ybarra', 138);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (94, 'Winn', 'Bauckham', 989);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (95, 'Donovan', 'De Normanville', 605);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (96, 'Red', 'Clemenzo', 972);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (97, 'Mella', 'Skypp', 72);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (98, 'Gelya', 'Toller', 424);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (99, 'Hebert', 'Willock', 279);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (100, 'Letitia', 'Dani', 636);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (101, 'Devonne', 'Raincin', 715);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (102, 'Chrisy', 'Duffy', 576);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (103, 'Catarina', 'Annetts', 727);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (104, 'Ira', 'Whiteford', 420);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (105, 'Zorina', 'Scarsbrick', 730);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (106, 'Cherie', 'Hubball', 935);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (107, 'Hagan', 'Tonbye', 290);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (108, 'Tillie', 'Linnell', 592);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (109, 'Joane', 'Sporgeon', 602);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (110, 'Gayla', 'Lunt', 532);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (111, 'Agathe', 'Ames', 146);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (112, 'Nanni', 'Rydeard', 353);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (113, 'Bidget', 'O''Heaney', 480);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (114, 'Jilli', 'Burbidge', 230);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (115, 'Tore', 'Twentyman', 4);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (116, 'Rheba', 'Kepp', 832);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (117, 'Zeb', 'Kidgell', 926);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (118, 'Donetta', 'McGrudder', 84);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (119, 'Jae', 'Navarijo', 843);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (120, 'Harman', 'Breyt', 395);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (121, 'Giselbert', 'Crank', 458);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (122, 'Karyn', 'Dorber', 382);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (123, 'Shirley', 'Bramwich', 859);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (124, 'Rickey', 'Tinn', 971);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (125, 'Laura', 'Snarie', 414);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (126, 'Reinold', 'Blackesland', 884);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (127, 'Sophi', 'Torrecilla', 205);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (128, 'Witty', 'McCaughey', 156);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (129, 'Emalee', 'Bartrop', 76);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (130, 'Keefer', 'Radolf', 662);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (131, 'Locke', 'Mannie', 32);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (132, 'Corry', 'Pudan', 230);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (133, 'Johna', 'Westraw', 117);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (134, 'Roseann', 'Baggot', 185);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (135, 'Alyss', 'Kemme', 643);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (136, 'Kirk', 'Legister', 95);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (137, 'Shandee', 'Gascone', 768);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (138, 'Liam', 'Marqyes', 320);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (139, 'Herschel', 'Culligan', 838);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (140, 'Alford', 'Osbourn', 309);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (141, 'Sheeree', 'Loncaster', 294);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (142, 'Che', 'Michele', 689);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (143, 'Eziechiele', 'Fox', 702);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (144, 'Masha', 'Shermar', 761);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (145, 'Madelon', 'Millberg', 644);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (146, 'Celestyna', 'Rentenbeck', 714);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (147, 'Quincey', 'Tellenbrok', 894);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (148, 'Valene', 'Garrie', 15);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (149, 'Milty', 'Fairey', 170);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (150, 'Addie', 'Yates', 251);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (151, 'Jenny', 'Marrow', 942);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (152, 'Tobias', 'Pledger', 847);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (153, 'Annmaria', 'Ginnety', 770);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (154, 'Ashia', 'Denisevich', 630);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (155, 'Alejoa', 'Minthorpe', 535);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (156, 'Pattin', 'Huggins', 266);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (157, 'Fonzie', 'Muckley', 867);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (158, 'Beltran', 'Christauffour', 72);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (159, 'Cully', 'Duckitt', 93);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (160, 'Maury', 'Maha', 557);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (161, 'Luce', 'Easby', 74);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (162, 'Onfre', 'Croote', 563);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (163, 'Gusella', 'McReedy', 92);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (164, 'Irina', 'Zannotti', 398);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (165, 'Pattin', 'Collerd', 419);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (166, 'Carrol', 'Forrington', 86);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (167, 'Hilliary', 'Onion', 947);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (168, 'Cordula', 'Stirling', 313);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (169, 'Sybila', 'Roebottom', 581);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (170, 'Rayner', 'Hartfield', 1);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (171, 'Norton', 'Scalia', 486);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (172, 'Raquela', 'Eneas', 233);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (173, 'Trescha', 'Noblet', 577);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (174, 'Rianon', 'Avrahamov', 244);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (175, 'Francisco', 'Manolov', 931);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (176, 'Glynis', 'Lanon', 654);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (177, 'Sebastien', 'Gantlett', 235);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (178, 'Nolly', 'Segebrecht', 107);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (179, 'Fannie', 'Spat', 270);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (180, 'Maure', 'Wolton', 989);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (181, 'Erena', 'Emslie', 789);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (182, 'Ari', 'Stroyan', 400);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (183, 'Genna', 'Quadling', 309);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (184, 'Arda', 'Blaik', 524);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (185, 'Rodrique', 'Trahar', 468);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (186, 'Phebe', 'Spondley', 947);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (187, 'Othelia', 'Caspell', 55);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (188, 'Isaac', 'Wernham', 445);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (189, 'Gweneth', 'Wilne', 536);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (190, 'Jim', 'Khristyukhin', 72);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (191, 'Averyl', 'Izakovitz', 913);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (192, 'Herminia', 'Matten', 871);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (193, 'Brent', 'Snape', 25);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (194, 'Kiele', 'Bingall', 119);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (195, 'Phyllys', 'Douthwaite', 1000);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (196, 'Marysa', 'Hogben', 823);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (197, 'Adriena', 'Hatchman', 659);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (198, 'Carey', 'Glasby', 969);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (199, 'Fayth', 'Prisk', 937);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (200, 'Biddie', 'Leatherbarrow', 268);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (201, 'Isis', 'Swalteridge', 161);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (202, 'Kirsti', 'Zelake', 471);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (203, 'Bernelle', 'Kline', 788);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (204, 'Antonetta', 'Nowlan', 401);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (205, 'Cassius', 'Piburn', 117);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (206, 'Gasparo', 'Kordt', 116);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (207, 'Selby', 'Muskett', 489);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (208, 'Theodore', 'Areles', 264);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (209, 'Prudence', 'Buffey', 162);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (210, 'Perle', 'Tomankowski', 793);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (211, 'Vicky', 'Cleft', 736);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (212, 'Liane', 'Ruslin', 790);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (213, 'Alfie', 'Grubbe', 973);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (214, 'Dolph', 'Abrahart', 680);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (215, 'Alana', 'Balharrie', 455);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (216, 'Christean', 'Backhurst', 541);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (217, 'Jacobo', 'Trollope', 456);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (218, 'Terra', 'Branscombe', 353);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (219, 'Oswald', 'Hammell', 900);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (220, 'Bobby', 'Chauvey', 268);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (221, 'Lula', 'Crosdill', 52);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (222, 'Roland', 'Capini', 27);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (223, 'Christopher', 'McComiskey', 288);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (224, 'Beverley', 'Gorvette', 387);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (225, 'Friederike', 'Carlisi', 533);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (226, 'Viola', 'Walak', 753);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (227, 'Belicia', 'Buttwell', 53);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (228, 'Ryun', 'Leijs', 376);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (229, 'Jermaine', 'Cadagan', 230);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (230, 'Yehudit', 'Geydon', 698);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (231, 'Charmane', 'Hawyes', 824);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (232, 'Cosmo', 'Doxey', 889);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (233, 'Abel', 'Hurn', 920);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (234, 'Teodor', 'Evensden', 54);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (235, 'Tedman', 'Ezzle', 946);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (236, 'Garland', 'Withur', 424);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (237, 'Harriett', 'Balaisot', 424);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (238, 'Rosa', 'Corbet', 742);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (239, 'Gabriele', 'Lembke', 796);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (240, 'Robinia', 'Linwood', 214);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (241, 'Oralee', 'Crosi', 483);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (242, 'Buiron', 'Vedenyapin', 949);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (243, 'Carlotta', 'Nucci', 804);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (244, 'Aldwin', 'Cowcha', 212);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (245, 'Marika', 'Coghill', 632);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (246, 'Moselle', 'Hryniewicki', 611);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (247, 'Robinson', 'Lockner', 11);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (248, 'Frederic', 'Craigheid', 413);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (249, 'Kitti', 'Flack', 706);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (250, 'Berti', 'Dowse', 516);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (251, 'Lyndel', 'Tourle', 882);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (252, 'Kev', 'Akess', 362);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (253, 'Hedi', 'Konzelmann', 215);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (254, 'Damaris', 'Petris', 28);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (255, 'Bette', 'Horlick', 154);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (256, 'Rahel', 'O''Finan', 647);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (257, 'Cristine', 'Osgordby', 915);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (258, 'Emelyne', 'Mc Combe', 540);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (259, 'Elvin', 'Alessandone', 172);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (260, 'Blinni', 'Allone', 444);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (261, 'Dorolice', 'Atlay', 90);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (262, 'Finley', 'Simoncello', 118);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (263, 'Elva', 'Newbold', 17);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (264, 'Mala', 'Blamphin', 703);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (265, 'Genna', 'Barg', 311);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (266, 'Maggie', 'Lawlor', 49);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (267, 'Georgi', 'Foakes', 516);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (268, 'Barbabra', 'Killingworth', 117);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (269, 'Bell', 'Chastang', 520);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (270, 'Merry', 'McIlhagga', 180);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (271, 'Jacqui', 'Mussington', 683);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (272, 'Puff', 'Wathell', 647);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (273, 'Lindon', 'Caselli', 590);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (274, 'Rem', 'Samples', 665);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (275, 'Isaiah', 'Brantzen', 279);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (276, 'Gerome', 'Goring', 272);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (277, 'Jacklin', 'Aldwinckle', 972);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (278, 'Lombard', 'Flannigan', 453);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (279, 'Northrup', 'Bockman', 347);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (280, 'Saxon', 'Meale', 773);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (281, 'Risa', 'Reimers', 298);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (282, 'Betti', 'Klaas', 675);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (283, 'Barbaraanne', 'O''Crowley', 186);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (284, 'Pall', 'Whiteley', 33);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (285, 'Allina', 'Briars', 329);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (286, 'Dun', 'Etchell', 923);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (287, 'Jared', 'Robberts', 36);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (288, 'Tyler', 'Domelow', 937);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (289, 'Kahaleel', 'Cushion', 823);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (290, 'Gustav', 'Crehan', 640);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (291, 'Bren', 'Solon', 944);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (292, 'Della', 'Boken', 386);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (293, 'Shalne', 'Rosenblad', 6);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (294, 'Evonne', 'Attewell', 252);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (295, 'Otha', 'Summerson', 741);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (296, 'Ajay', 'Balle', 537);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (297, 'Anastasie', 'Kingman', 64);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (298, 'Moselle', 'Shires', 811);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (299, 'Michaella', 'Bordessa', 745);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (300, 'Aldridge', 'Cowdroy', 489);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (301, 'Saundra', 'Thorsen', 248);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (302, 'Karmen', 'Harmour', 339);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (303, 'Rosabella', 'Rosenfrucht', 381);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (304, 'Ringo', 'Frift', 454);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (305, 'Jayson', 'Spohrmann', 766);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (306, 'Scottie', 'Sonley', 228);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (307, 'Lelia', 'Manterfield', 749);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (308, 'Daphne', 'Riddington', 603);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (309, 'Bink', 'Berr', 226);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (310, 'Amalia', 'Brimblecombe', 132);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (311, 'Gustaf', 'Felgate', 990);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (312, 'Karyl', 'Rosenwald', 58);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (313, 'Thea', 'Helbeck', 147);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (314, 'Anallese', 'Blockwell', 28);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (315, 'Aridatha', 'Linfitt', 102);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (316, 'Cindra', 'O''Doherty', 239);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (317, 'Selinda', 'Stanway', 926);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (318, 'Shaun', 'Arrigo', 462);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (319, 'Deck', 'Daouze', 226);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (320, 'Barr', 'Rayman', 937);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (321, 'Jordon', 'Stubbe', 954);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (322, 'Elane', 'Dregan', 58);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (323, 'Davita', 'Taudevin', 1);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (324, 'Towney', 'Gates', 200);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (325, 'Anallese', 'Szymaniak', 839);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (326, 'Kort', 'Novotne', 503);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (327, 'Cordie', 'Rama', 83);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (328, 'Thorny', 'Kures', 44);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (329, 'Reba', 'Durdle', 438);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (330, 'Patrice', 'Farrants', 298);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (331, 'Suzy', 'Moorey', 336);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (332, 'Barth', 'Pelos', 310);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (333, 'Bord', 'Perri', 619);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (334, 'Penrod', 'Furness', 620);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (335, 'Lilla', 'La Torre', 691);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (336, 'Dorotea', 'Kennard', 287);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (337, 'Hogan', 'Whitehouse', 478);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (338, 'Pippy', 'Tyhurst', 365);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (339, 'Marigold', 'Kenny', 125);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (340, 'Brigida', 'Hucks', 115);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (341, 'Amerigo', 'Ingerith', 441);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (342, 'Dorolisa', 'Garbett', 37);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (343, 'Constantina', 'Malbon', 385);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (344, 'Anthe', 'Bleaden', 225);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (345, 'Ashely', 'Cogar', 698);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (346, 'Lilly', 'Alfonsetto', 133);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (347, 'Letisha', 'Benech', 647);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (348, 'Toby', 'Pirkis', 847);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (349, 'Elle', 'Primrose', 154);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (350, 'Skipper', 'Sage', 934);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (351, 'Sheena', 'Woodhouse', 765);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (352, 'Lizzy', 'Favelle', 767);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (353, 'Franklyn', 'Yare', 42);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (354, 'Ondrea', 'Nicolls', 702);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (355, 'Tommie', 'Flann', 590);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (356, 'Paulette', 'Collerd', 852);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (357, 'Juliette', 'Hutchings', 629);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (358, 'Fulvia', 'Landsberg', 1);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (359, 'Marcile', 'Dring', 609);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (360, 'Brunhilda', 'Ricardet', 203);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (361, 'Baillie', 'Abramovitch', 552);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (362, 'Amil', 'Ciepluch', 215);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (363, 'Desiri', 'Sumption', 918);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (364, 'Urbain', 'Rosbotham', 79);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (365, 'Mal', 'Kelk', 254);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (366, 'Luis', 'De Mitri', 899);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (367, 'Sharl', 'Scarsbrick', 323);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (368, 'Coletta', 'Pavlishchev', 81);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (369, 'Elaina', 'Quinion', 433);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (370, 'Sabine', 'Houldcroft', 971);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (371, 'Corilla', 'Whiff', 694);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (372, 'Odessa', 'Crowdace', 838);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (373, 'Philly', 'Patrono', 942);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (374, 'Mimi', 'Peirone', 731);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (375, 'Jamey', 'Acuna', 440);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (376, 'Loise', 'Badsey', 243);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (377, 'Shep', 'Kenworthey', 8);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (378, 'Clara', 'Casham', 943);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (379, 'Agosto', 'Mouser', 641);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (380, 'Erroll', 'Kilford', 369);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (381, 'Lottie', 'Alpes', 889);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (382, 'Danni', 'Lazonby', 637);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (383, 'Imogen', 'Snashall', 119);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (384, 'Abbe', 'Gilchrest', 65);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (385, 'Chris', 'Brasted', 77);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (386, 'Junia', 'Kelson', 677);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (387, 'Abbie', 'Leaman', 809);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (388, 'Artur', 'Ramm', 197);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (389, 'Miranda', 'Dredge', 207);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (390, 'Noah', 'Kingham', 794);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (391, 'Carmelle', 'Meade', 296);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (392, 'Erny', 'Woolliams', 227);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (393, 'Cordelia', 'Ingram', 236);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (394, 'Julee', 'Letrange', 425);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (395, 'Zebulen', 'D''Ambrosio', 346);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (396, 'Gay', 'Swadlinge', 416);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (397, 'Moina', 'Robjents', 25);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (398, 'Edd', 'Smythin', 770);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (399, 'Skylar', 'Rosenhaus', 240);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (400, 'Tawsha', 'Gatherer', 316);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (401, 'Evangelina', 'Delgua', 543);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (402, 'Kylie', 'Camoletto', 645);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (403, 'Dallis', 'D''Costa', 711);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (404, 'Emlyn', 'Josey', 899);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (405, 'Ola', 'Whimp', 84);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (406, 'Effie', 'Keyte', 556);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (407, 'Teodor', 'Braunstein', 242);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (408, 'Issy', 'Winders', 883);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (409, 'Aida', 'Duddell', 885);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (410, 'Flint', 'Kermon', 267);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (411, 'Trisha', 'Trude', 753);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (412, 'Farr', 'Cobson', 206);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (413, 'Sandra', 'Horlock', 804);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (414, 'Janith', 'Garstang', 868);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (415, 'Lucho', 'Juan', 905);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (416, 'Callean', 'Crolly', 722);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (417, 'Rafaelita', 'De Beauchemp', 51);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (418, 'Perrine', 'Shwenn', 987);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (419, 'Mureil', 'Mattei', 466);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (420, 'Mycah', 'Kernar', 676);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (421, 'Consuela', 'Gouldthorpe', 702);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (422, 'Dottie', 'Sumner', 514);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (423, 'Barnabe', 'Eggleson', 178);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (424, 'Gustaf', 'Hunstone', 709);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (425, 'Emiline', 'Cressy', 858);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (426, 'Gilberta', 'Sowood', 783);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (427, 'Nobe', 'Crosfeld', 717);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (428, 'Gonzalo', 'Woodruff', 635);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (429, 'Cookie', 'MacDirmid', 530);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (430, 'Erminia', 'Kennea', 237);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (431, 'Duky', 'Rayson', 141);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (432, 'Adela', 'Rudgley', 913);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (433, 'Cornelius', 'Mattholie', 328);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (434, 'Scarface', 'Bruno', 1);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (435, 'Cullen', 'Skin', 26);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (436, 'Otes', 'Dally', 754);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (437, 'Gloriana', 'Brogi', 666);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (438, 'Charley', 'Keepin', 862);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (439, 'Janos', 'Cobon', 256);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (440, 'Ody', 'Braund', 8);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (441, 'Gardener', 'Stracey', 129);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (442, 'Noach', 'Paskin', 393);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (443, 'Kellia', 'Walkowski', 481);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (444, 'Daryle', 'Gilbard', 990);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (445, 'Orren', 'Engledow', 900);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (446, 'Johann', 'Render', 641);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (447, 'Cart', 'Burleigh', 284);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (448, 'Giralda', 'MacMorland', 146);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (449, 'Ashia', 'Nudd', 210);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (450, 'Evan', 'Chatelet', 436);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (451, 'Ruprecht', 'MacRory', 443);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (452, 'Nani', 'Cornelisse', 395);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (453, 'Will', 'Depke', 81);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (454, 'Randell', 'Mateus', 206);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (455, 'Bobette', 'Ridsdell', 735);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (456, 'Barris', 'Wilsher', 650);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (457, 'Elie', 'Glyne', 54);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (458, 'Garrek', 'Casine', 767);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (459, 'Melantha', 'Lishman', 495);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (460, 'Alfie', 'Bertram', 95);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (461, 'Devon', 'Sawer', 990);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (462, 'Malvin', 'Cains', 303);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (463, 'Yardley', 'Vogt', 955);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (464, 'Merrili', 'Cleynaert', 765);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (465, 'Brendis', 'Grishaev', 744);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (466, 'Meghann', 'Pencot', 288);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (467, 'Wheeler', 'Dymick', 679);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (468, 'Karrah', 'Isles', 655);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (469, 'Burgess', 'Tumielli', 945);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (470, 'Abe', 'Truckett', 128);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (471, 'Agneta', 'Crowth', 853);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (472, 'Giuditta', 'Gillian', 686);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (473, 'Emiline', 'Jozsef', 809);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (474, 'Codi', 'MacAscaidh', 278);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (475, 'Conan', 'Aiskrigg', 345);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (476, 'Filippa', 'Fryman', 323);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (477, 'Faun', 'Larcombe', 77);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (478, 'Shepard', 'Clarkin', 43);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (479, 'Delainey', 'Will', 373);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (480, 'Broddie', 'Cuff', 431);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (481, 'Mellicent', 'Etuck', 124);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (482, 'Sutherlan', 'Corish', 297);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (483, 'Marthe', 'Rogister', 435);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (484, 'Cory', 'Worley', 242);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (485, 'Mildrid', 'Coan', 441);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (486, 'Felicity', 'Byers', 350);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (487, 'Odilia', 'Verney', 74);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (488, 'Jayson', 'Robertson', 940);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (489, 'Theodoric', 'Wetherell', 836);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (490, 'Lise', 'Moakes', 668);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (491, 'Fianna', 'Boughtflower', 883);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (492, 'Darbee', 'Goody', 588);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (493, 'Sheree', 'Eastgate', 188);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (494, 'Shane', 'McAllister', 572);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (495, 'Leora', 'Applebee', 481);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (496, 'Chip', 'Alpes', 460);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (497, 'Lia', 'Clowes', 431);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (498, 'Prince', 'Crocken', 166);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (499, 'Darleen', 'Kordova', 725);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (500, 'Hill', 'Peller', 974);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (501, 'Corinna', 'MacIver', 869);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (502, 'Charlena', 'Cotter', 725);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (503, 'Domeniga', 'Slimm', 506);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (504, 'Twila', 'Roderigo', 571);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (505, 'Brigid', 'Brosnan', 236);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (506, 'Archy', 'Oller', 292);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (507, 'Jobyna', 'Kardos', 30);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (508, 'Pooh', 'Cakebread', 991);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (509, 'Bary', 'Riggeard', 57);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (510, 'Rip', 'Limpricht', 342);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (511, 'Frazer', 'Permain', 350);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (512, 'Budd', 'Linsey', 420);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (513, 'Tally', 'Brayfield', 552);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (514, 'Gillie', 'Ilem', 197);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (515, 'Merrile', 'Nickoll', 880);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (516, 'Ariel', 'Manueau', 713);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (517, 'Ginnifer', 'Mitrovic', 208);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (518, 'Amii', 'MacSwayde', 273);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (519, 'Lauretta', 'Tristram', 260);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (520, 'Erhard', 'Casterot', 106);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (521, 'Herc', 'Gerardet', 530);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (522, 'Orella', 'Monckton', 434);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (523, 'Tomlin', 'Dilger', 419);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (524, 'Mahmud', 'Careless', 631);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (525, 'Tom', 'Cockill', 201);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (526, 'Jaimie', 'Whitehouse', 118);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (527, 'Cedric', 'Greason', 466);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (528, 'Gavrielle', 'Senior', 820);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (529, 'Lavena', 'Sawood', 96);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (530, 'Dacie', 'Clegg', 237);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (531, 'Selene', 'Quig', 751);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (532, 'Ulrick', 'Teece', 235);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (533, 'Kasey', 'Inglis', 621);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (534, 'Lisetta', 'Veld', 709);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (535, 'Sonnie', 'Keaysell', 57);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (536, 'Candida', 'Benge', 989);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (537, 'Valli', 'Wallworke', 82);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (538, 'Estrellita', 'Peller', 88);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (539, 'Wain', 'Sedgemore', 825);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (540, 'Oran', 'MacRedmond', 595);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (541, 'Morlee', 'Philps', 47);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (542, 'Isahella', 'Oneil', 253);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (543, 'Jayme', 'Barmadier', 105);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (544, 'Berry', 'Klambt', 272);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (545, 'Willabella', 'Carthy', 225);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (546, 'Kendricks', 'Samples', 201);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (547, 'Vinny', 'Applin', 418);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (548, 'Ravid', 'Upstell', 400);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (549, 'Desdemona', 'O''Meara', 907);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (550, 'Inge', 'Rampley', 530);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (551, 'Fiona', 'Cardis', 479);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (552, 'Christoffer', 'Rable', 137);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (553, 'Pernell', 'Lanphier', 981);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (554, 'Nanette', 'Cirlos', 265);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (555, 'Avril', 'Feveryear', 236);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (556, 'Fredelia', 'Copper', 665);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (557, 'Kincaid', 'McPhilemy', 982);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (558, 'Lona', 'Assiter', 42);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (559, 'Daffie', 'Ropcke', 219);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (560, 'Sybila', 'Greening', 797);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (561, 'Katrine', 'Stocks', 226);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (562, 'Otis', 'Stidston', 870);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (563, 'Elicia', 'Joire', 431);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (564, 'Athena', 'Brettor', 620);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (565, 'Beatrice', 'Farress', 564);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (566, 'Giulia', 'Poyner', 632);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (567, 'Katharine', 'Crowd', 799);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (568, 'Bea', 'Drayn', 433);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (569, 'Kordula', 'Schonfelder', 960);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (570, 'Howard', 'Hanna', 247);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (571, 'Myranda', 'Wait', 943);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (572, 'Johnna', 'Devericks', 689);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (573, 'Kaleb', 'Wharton', 234);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (574, 'Alison', 'Biaggelli', 49);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (575, 'Jena', 'Tilliards', 964);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (576, 'Kordula', 'Kenworth', 898);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (577, 'Loralyn', 'Rabbage', 125);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (578, 'Hurley', 'Sterrie', 278);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (579, 'Dollie', 'Matuschek', 555);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (580, 'Jeffie', 'Schwandt', 967);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (581, 'Tann', 'Clemendot', 942);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (582, 'Gertrudis', 'Neilson', 829);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (583, 'Chaddy', 'Oxlade', 961);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (584, 'Victor', 'Eccleshall', 669);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (585, 'Nil', 'Coates', 76);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (586, 'Rodina', 'Schaumann', 750);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (587, 'Dane', 'Dunbabin', 318);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (588, 'Jonie', 'Chattelaine', 927);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (589, 'Luci', 'Brooke', 274);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (590, 'Sigismundo', 'Kretchmer', 551);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (591, 'Nellie', 'Kenewell', 123);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (592, 'Oralie', 'Groarty', 231);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (593, 'Hadleigh', 'Harrap', 19);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (594, 'Rosanna', 'Giriardelli', 253);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (595, 'Cyndy', 'Vynall', 94);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (596, 'Carroll', 'Imos', 416);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (597, 'Ellis', 'Winterborne', 439);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (598, 'Wye', 'Pavlishchev', 647);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (599, 'Bar', 'O''Murtagh', 423);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (600, 'Basilius', 'Lokier', 909);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (601, 'Danita', 'Dello', 622);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (602, 'Joanie', 'Dowbekin', 198);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (603, 'Colman', 'Duggon', 926);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (604, 'Munroe', 'Umpleby', 410);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (605, 'Gloriane', 'Kezar', 557);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (606, 'Paco', 'Seagood', 346);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (607, 'Jasun', 'Dayley', 246);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (608, 'Geneva', 'Tuting', 888);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (609, 'Earvin', 'Dumbrall', 180);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (610, 'Anne', 'Scedall', 232);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (611, 'Rebekkah', 'Kensitt', 749);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (612, 'Robbert', 'Hardy-Piggin', 974);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (613, 'Rees', 'Jentet', 299);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (614, 'Mariel', 'Hymers', 466);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (615, 'Sheffield', 'Hodjetts', 877);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (616, 'Kareem', 'Robarts', 724);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (617, 'Bret', 'Klimke', 230);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (618, 'Arlen', 'Blazey', 521);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (619, 'Duffy', 'Chung', 118);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (620, 'Jason', 'Cowmeadow', 508);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (621, 'Amara', 'Hackett', 477);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (622, 'Glynis', 'Williment', 999);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (623, 'Melisse', 'Iley', 336);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (624, 'Camille', 'Angeli', 404);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (625, 'Leeanne', 'O''Neill', 280);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (626, 'Reginald', 'Duthie', 66);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (627, 'Deck', 'Strelitzer', 657);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (628, 'Kiley', 'McNiven', 508);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (629, 'Waite', 'Ashburner', 108);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (630, 'Pammy', 'Castiglioni', 933);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (631, 'Joyan', 'Hamblyn', 270);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (632, 'Pavla', 'Trayton', 5);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (633, 'Irene', 'Segebrecht', 158);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (634, 'Mylo', 'Liddyard', 589);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (635, 'Lindsey', 'Popley', 529);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (636, 'Claire', 'Vedenichev', 325);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (637, 'Abby', 'Leckie', 383);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (638, 'Gill', 'Giacobo', 743);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (639, 'Rosamond', 'Mahood', 354);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (640, 'Fons', 'Danilchev', 915);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (641, 'Deeanne', 'Olney', 733);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (642, 'Artemus', 'Kilcoyne', 167);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (643, 'Xenos', 'Linnane', 948);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (644, 'Gabe', 'Maunder', 425);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (645, 'Valli', 'Attryde', 262);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (646, 'Kimberli', 'Sains', 336);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (647, 'Jaquelin', 'Welburn', 16);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (648, 'Wald', 'Grannell', 793);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (649, 'Keri', 'McLarty', 264);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (650, 'Werner', 'Lamar', 519);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (651, 'Ebenezer', 'Chase', 155);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (652, 'Stefa', 'Rangell', 862);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (653, 'Meir', 'Pengilly', 295);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (654, 'Catlee', 'Hendriks', 618);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (655, 'Juliane', 'Davio', 656);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (656, 'Ebeneser', 'Benediktsson', 436);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (657, 'Lacie', 'Mullin', 515);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (658, 'Abie', 'Halfhide', 537);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (659, 'Osmund', 'Towson', 414);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (660, 'Keefe', 'Blackmore', 836);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (661, 'Pippa', 'Pryor', 510);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (662, 'Amaleta', 'Fincham', 291);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (663, 'Griff', 'Harkness', 876);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (664, 'Linc', 'Vant', 958);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (665, 'Ranice', 'Magor', 33);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (666, 'Lia', 'Doring', 384);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (667, 'Onida', 'Iacobacci', 144);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (668, 'Iosep', 'Drife', 752);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (669, 'Tate', 'Bonhill', 522);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (670, 'Ax', 'Pflieger', 149);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (671, 'Adoree', 'MacKibbon', 777);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (672, 'Chrystal', 'Corrao', 890);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (673, 'Florenza', 'Swires', 324);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (674, 'Bertha', 'Leake', 146);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (675, 'Elsie', 'Rickis', 253);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (676, 'Bonnibelle', 'Jaan', 129);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (677, 'Gipsy', 'Yerbury', 625);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (678, 'Chaddy', 'Wagg', 161);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (679, 'Kaylil', 'Cleal', 567);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (680, 'Joscelin', 'Bome', 832);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (681, 'Margie', 'Spark', 993);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (682, 'Karlens', 'Leavold', 800);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (683, 'Zsa zsa', 'Himsworth', 94);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (684, 'Adolphe', 'Ollivier', 212);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (685, 'Alfie', 'Tukesby', 161);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (686, 'Montague', 'Ramsbottom', 678);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (687, 'Roanne', 'Jorioz', 940);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (688, 'Vladimir', 'Haker', 550);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (689, 'Celestyn', 'Nund', 417);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (690, 'Tristan', 'Poznan', 741);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (691, 'Jamey', 'Gullyes', 651);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (692, 'Erena', 'Jantel', 467);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (693, 'Elna', 'Grishanov', 234);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (694, 'Rafaela', 'Hatchard', 718);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (695, 'Kitti', 'Davidge', 100);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (696, 'Afton', 'Slainey', 547);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (697, 'Lorenzo', 'Rosie', 25);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (698, 'Sutherland', 'Dryburgh', 840);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (699, 'Stesha', 'Lohrensen', 809);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (700, 'Mead', 'Riseam', 340);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (701, 'Vance', 'Kynvin', 274);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (702, 'Eward', 'Cazin', 838);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (703, 'Sybil', 'Canape', 783);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (704, 'Shell', 'Gilffilland', 458);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (705, 'Arty', 'Peasgood', 710);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (706, 'Claudette', 'Martinez', 191);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (707, 'Theresina', 'Jerman', 728);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (708, 'Tish', 'Barson', 844);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (709, 'Roslyn', 'Feeney', 216);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (710, 'Florri', 'Van Haeften', 778);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (711, 'Corney', 'Rolston', 388);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (712, 'Rudie', 'Monteath', 935);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (713, 'Skyler', 'Dalgetty', 652);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (714, 'Lucilia', 'Kenwrick', 975);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (715, 'Fergus', 'Kiffin', 203);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (716, 'Briana', 'Wrigley', 864);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (717, 'Morgen', 'Kiledal', 464);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (718, 'Maisie', 'Deakan', 62);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (719, 'Danell', 'Creany', 137);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (720, 'Ericka', 'Lanfer', 70);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (721, 'Jillie', 'Hodge', 431);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (722, 'Archibald', 'Gyppes', 438);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (723, 'Bianca', 'Ritter', 184);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (724, 'Conrad', 'Masedon', 606);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (725, 'Worthy', 'Deschelle', 188);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (726, 'Rodger', 'Boddice', 981);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (727, 'Goldia', 'Casbourne', 231);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (728, 'Huey', 'Liddon', 651);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (729, 'Hillier', 'Dobing', 844);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (730, 'Nara', 'Shortall', 413);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (731, 'Kristen', 'Paget', 528);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (732, 'Barty', 'Woodberry', 429);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (733, 'Robbert', 'Elfes', 651);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (734, 'Willa', 'Ackeroyd', 840);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (735, 'Kalindi', 'Beedom', 19);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (736, 'Trixy', 'Abrey', 583);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (737, 'Susy', 'Curwen', 937);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (738, 'Etheline', 'Broadbridge', 506);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (739, 'Annabella', 'Franken', 731);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (740, 'Wynne', 'Bartalot', 248);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (741, 'Caron', 'Danko', 433);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (742, 'Roma', 'Cairney', 788);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (743, 'Darcee', 'Crocombe', 645);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (744, 'Rodney', 'Remmers', 118);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (745, 'Brigid', 'Aldcorne', 941);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (746, 'Phylis', 'Daulby', 877);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (747, 'Berne', 'Thuillier', 226);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (748, 'Simon', 'Ragsdale', 108);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (749, 'Kenneth', 'Connah', 1000);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (750, 'Calida', 'McGann', 397);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (751, 'Rodolph', 'Coneybeare', 712);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (752, 'Reba', 'Hatt', 689);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (753, 'Claribel', 'Skelbeck', 741);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (754, 'Noll', 'Hughf', 797);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (755, 'Jackquelin', 'Barrott', 657);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (756, 'Madella', 'Hobbing', 744);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (757, 'Pincus', 'Tettley', 722);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (758, 'Bing', 'Bolley', 149);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (759, 'Frazer', 'Blinde', 196);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (760, 'Mady', 'Berwick', 937);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (761, 'Nolana', 'Rupert', 290);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (762, 'Nobe', 'Prescote', 179);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (763, 'Bancroft', 'Lurriman', 72);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (764, 'Judah', 'Sharrem', 937);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (765, 'Clarke', 'Proudley', 728);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (766, 'Hamlen', 'Ballinger', 163);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (767, 'Ervin', 'McChruiter', 825);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (768, 'Karlens', 'Insley', 751);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (769, 'Rog', 'Sisneros', 207);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (770, 'Irv', 'Crich', 182);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (771, 'Dale', 'Legion', 811);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (772, 'Serena', 'Pollett', 166);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (773, 'Waiter', 'Rollo', 384);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (774, 'Abdel', 'Inglesant', 607);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (775, 'Marrilee', 'Gavozzi', 663);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (776, 'Basile', 'Rawsthorne', 342);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (777, 'Vanda', 'Meddemmen', 220);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (778, 'Kessia', 'Breheny', 189);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (779, 'Hewet', 'Rigardeau', 133);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (780, 'Morgana', 'Cargill', 963);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (781, 'Arty', 'Clift', 531);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (782, 'Iona', 'Mangam', 185);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (783, 'My', 'Rabier', 105);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (784, 'Reese', 'Strowlger', 182);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (785, 'Sonni', 'Camellini', 235);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (786, 'Arie', 'Le Barre', 556);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (787, 'Shanta', 'Kennedy', 868);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (788, 'Harper', 'Mandeville', 198);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (789, 'Elysha', 'Stredder', 735);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (790, 'Marcelia', 'Widmore', 83);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (791, 'Eilis', 'De Antoni', 846);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (792, 'Gael', 'McKennan', 665);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (793, 'Correy', 'Clougher', 238);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (794, 'Hillery', 'Melladew', 248);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (795, 'Hesther', 'Schuricht', 519);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (796, 'Simeon', 'Brannigan', 552);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (797, 'Rosabel', 'Moryson', 935);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (798, 'Welbie', 'Dunkersley', 848);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (799, 'Perren', 'Golde', 810);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (800, 'Stinky', 'Velten', 417);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (801, 'Eugen', 'Gutridge', 474);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (802, 'Micah', 'Stare', 709);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (803, 'Erda', 'Stonebanks', 193);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (804, 'Horten', 'Speakman', 962);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (805, 'Prissie', 'Crow', 883);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (806, 'Corrie', 'Hoodlass', 620);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (807, 'Jo ann', 'Bland', 656);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (808, 'Obidiah', 'Cortes', 407);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (809, 'Stern', 'Summerside', 4);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (810, 'Lemuel', 'Makin', 444);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (811, 'Maia', 'Duplain', 146);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (812, 'Dodie', 'Lesslie', 44);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (813, 'Murray', 'Carratt', 726);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (814, 'Daron', 'Kidney', 127);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (815, 'Finlay', 'Corona', 111);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (816, 'Cynthie', 'Redit', 274);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (817, 'Johannes', 'Burgh', 174);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (818, 'Waneta', 'Rasor', 477);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (819, 'Joelie', 'Hawyes', 846);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (820, 'Harley', 'Astling', 86);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (821, 'Ward', 'Sidebottom', 919);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (822, 'Georgianna', 'Dany', 439);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (823, 'Eugen', 'Zamudio', 745);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (824, 'Carr', 'Arnholz', 532);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (825, 'Doria', 'Bosher', 463);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (826, 'Frederigo', 'Adcock', 461);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (827, 'Bord', 'Croysdale', 106);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (828, 'Thor', 'Rozycki', 758);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (829, 'Michel', 'Meany', 119);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (830, 'Haskell', 'Hodgin', 764);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (831, 'Aubine', 'Isoldi', 375);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (832, 'Dalenna', 'Adao', 263);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (833, 'Nadiya', 'Malkie', 839);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (834, 'La verne', 'Basterfield', 425);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (835, 'Wakefield', 'Mohammed', 844);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (836, 'Sandor', 'Udie', 945);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (837, 'Barbabra', 'Yeliashev', 581);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (838, 'Arlene', 'Redparth', 964);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (839, 'Em', 'Towne', 697);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (840, 'Whittaker', 'Andrich', 291);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (841, 'Loise', 'Kettlewell', 441);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (842, 'Mauricio', 'Whitebread', 568);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (843, 'Monique', 'Korejs', 854);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (844, 'Hi', 'Hazeldene', 426);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (845, 'Minerva', 'Gudge', 305);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (846, 'Lanae', 'Kitchingman', 804);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (847, 'Leia', 'Ilyas', 923);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (848, 'Dill', 'Patullo', 781);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (849, 'Arnaldo', 'Siegertsz', 905);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (850, 'Cristin', 'Heady', 680);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (851, 'Sherline', 'Segar', 859);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (852, 'Rudiger', 'Duny', 712);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (853, 'Johnny', 'Stoakes', 54);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (854, 'Colleen', 'Scarffe', 588);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (855, 'Wally', 'Strickland', 101);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (856, 'Georgeta', 'Sibthorp', 674);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (857, 'Field', 'Rosenzveig', 737);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (858, 'Derk', 'Alessandone', 220);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (859, 'Bethanne', 'Silverlock', 263);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (860, 'Wes', 'Dibling', 74);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (861, 'Dene', 'Elkington', 876);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (862, 'Thelma', 'Winterbourne', 924);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (863, 'Rosabella', 'Lount', 316);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (864, 'Harriette', 'Tummasutti', 234);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (865, 'Eberhard', 'Halwell', 155);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (866, 'Ermina', 'Van Hesteren', 338);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (867, 'Sher', 'Sibson', 572);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (868, 'Hedvig', 'Vel', 265);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (869, 'Barty', 'Leate', 311);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (870, 'Sella', 'Sprott', 352);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (871, 'Wilone', 'Shoosmith', 489);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (872, 'Cathee', 'Vinsen', 663);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (873, 'Tremaine', 'Baylie', 338);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (874, 'Giulio', 'Hammant', 631);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (875, 'Mike', 'Rugiero', 361);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (876, 'Baryram', 'Freezer', 286);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (877, 'Reggy', 'Binford', 841);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (878, 'Lynelle', 'Speir', 393);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (879, 'Teresita', 'Rumney', 590);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (880, 'Sanson', 'Boater', 834);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (881, 'Vaughan', 'Riccione', 667);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (882, 'Bethina', 'Croutear', 279);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (883, 'Lawrence', 'Empringham', 805);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (884, 'Nicolis', 'Harriagn', 522);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (885, 'Swen', 'Borland', 953);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (886, 'Sabrina', 'Gillbanks', 410);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (887, 'Thedrick', 'Crielly', 769);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (888, 'Henri', 'Ilymanov', 898);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (889, 'Artie', 'Cocksedge', 626);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (890, 'Kent', 'Orae', 366);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (891, 'Jerad', 'Ingilson', 89);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (892, 'Mikey', 'Couttes', 821);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (893, 'Melinde', 'Giacomucci', 110);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (894, 'Trixie', 'Lillecrop', 232);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (895, 'Dolf', 'Parsonson', 993);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (896, 'Rikki', 'MacKeig', 637);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (897, 'Damara', 'Faire', 539);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (898, 'Wendeline', 'Kearney', 196);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (899, 'Melodie', 'Rust', 694);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (900, 'Sal', 'Lamborne', 245);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (901, 'Oralie', 'Barke', 713);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (902, 'Lissi', 'Aspinall', 995);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (903, 'Millard', 'Aspital', 108);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (904, 'Gayelord', 'Burlingame', 107);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (905, 'Darla', 'Bendare', 284);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (906, 'Lek', 'Mattholie', 91);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (907, 'Celeste', 'Cleef', 768);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (908, 'Giustino', 'Machans', 102);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (909, 'Lennie', 'Hartas', 899);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (910, 'Fleurette', 'McTerrelly', 17);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (911, 'Sybyl', 'Janoschek', 535);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (912, 'Fanny', 'Douris', 301);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (913, 'Annaliese', 'Game', 993);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (914, 'Shayna', 'Bercher', 469);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (915, 'Danyette', 'Skinley', 982);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (916, 'Thibaud', 'Mauchline', 538);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (917, 'Christabella', 'Kingsworth', 822);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (918, 'Godfry', 'Mion', 857);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (919, 'Lucho', 'Buzine', 92);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (920, 'Felike', 'McLaverty', 313);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (921, 'Odey', 'Yu', 377);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (922, 'Court', 'Wadly', 149);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (923, 'Derril', 'Denes', 445);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (924, 'Finlay', 'Leguay', 965);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (925, 'Susan', 'Chavrin', 892);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (926, 'Cherrita', 'McIlraith', 698);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (927, 'Louie', 'Dusting', 303);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (928, 'Dewain', 'Dymott', 615);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (929, 'Boote', 'Borres', 955);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (930, 'Prudi', 'Emons', 628);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (931, 'Emanuele', 'Maun', 575);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (932, 'Dionis', 'Koschke', 814);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (933, 'Lola', 'Pickerin', 628);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (934, 'Merle', 'Newns', 590);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (935, 'Leif', 'Cornfield', 59);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (936, 'Skell', 'O''Gaven', 953);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (937, 'Dahlia', 'Neillans', 755);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (938, 'Virgie', 'Forrestall', 118);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (939, 'Madlen', 'Gwatkins', 593);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (940, 'Ely', 'Niblo', 593);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (941, 'Tomasine', 'Tebb', 483);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (942, 'Oralla', 'Marrett', 81);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (943, 'Sybilla', 'Schwandermann', 468);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (944, 'Boot', 'Ridger', 428);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (945, 'Lenka', 'Lardnar', 208);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (946, 'Shandee', 'Houseago', 506);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (947, 'Ximenez', 'Emma', 378);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (948, 'Golda', 'Higgen', 414);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (949, 'Araldo', 'Melesk', 355);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (950, 'Adriano', 'Gergolet', 10);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (951, 'Marya', 'Haggarty', 819);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (952, 'Fletch', 'Davsley', 676);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (953, 'Merilee', 'Robbey', 305);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (954, 'Lyssa', 'Casaro', 685);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (955, 'Abey', 'Carlick', 85);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (956, 'Anton', 'Farrington', 223);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (957, 'Stephanie', 'Boullen', 188);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (958, 'Leeanne', 'Coch', 939);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (959, 'Gabriellia', 'Bannester', 814);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (960, 'Hermon', 'Gaunt', 905);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (961, 'Beau', 'Kirtlan', 243);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (962, 'Lizzie', 'Le Claire', 92);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (963, 'Yolane', 'Wyleman', 93);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (964, 'Yvon', 'Kipling', 221);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (965, 'Kingsly', 'Thoma', 510);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (966, 'Georg', 'Labuschagne', 124);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (967, 'Kingsly', 'Abbotts', 597);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (968, 'Ricardo', 'Lunck', 901);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (969, 'Barbi', 'Schukraft', 432);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (970, 'Misty', 'Longstreet', 707);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (971, 'Dorella', 'Dyton', 829);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (972, 'Olive', 'Base', 584);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (973, 'Powell', 'Hedworth', 643);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (974, 'Helsa', 'Roggero', 711);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (975, 'Flem', 'Neachell', 938);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (976, 'Lynnette', 'Arent', 351);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (977, 'Milt', 'Broose', 61);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (978, 'Jemie', 'Duff', 854);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (979, 'Shanan', 'Tuppeny', 959);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (980, 'Debor', 'Bickell', 839);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (981, 'Byrom', 'Tarrier', 483);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (982, 'Fraze', 'Cregan', 186);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (983, 'Joan', 'Shovelin', 496);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (984, 'Gianina', 'Tulk', 935);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (985, 'Emmery', 'Portail', 86);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (986, 'Bing', 'Tipler', 936);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (987, 'Danette', 'Domingues', 350);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (988, 'Royall', 'Gilby', 167);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (989, 'Anett', 'Hamm', 170);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (990, 'Audy', 'Whybray', 535);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (991, 'Derrik', 'Fery', 220);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (992, 'Eunice', 'Roddam', 385);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (993, 'Bonnibelle', 'Whittlesee', 477);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (994, 'Cameron', 'Jouaneton', 871);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (995, 'Ethel', 'Cradock', 615);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (996, 'Humbert', 'Santarelli', 407);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (997, 'Chicky', 'Cootes', 68);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (998, 'Rani', 'Bonnett', 708);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (999, 'Dreddy', 'McCreagh', 785);

INSERT INTO CUSTOMER (ID, NAME, SURNAME, ADDRESSID) 
VALUES (1000, 'Elga', 'Deppe', 465);

-- Import Data into table CUSTOMER from file C:\Users\Piotr\Downloads\MOCK_DATA (6).csv . Task successful and sent to worksheet.
