
-- foreign keys
-- Reference: ADDRESS_CUSTOMER (table: CUSTOMER)
ALTER TABLE CUSTOMER ADD CONSTRAINT ADDRESS_CUSTOMER
    FOREIGN KEY (AddressId)
    REFERENCES Address (Id);

-- Reference: ADDRESS_DEALERSHIP (table: DEALERSHIP)
ALTER TABLE DEALERSHIP ADD CONSTRAINT ADDRESS_DEALERSHIP
    FOREIGN KEY (AddressId)
    REFERENCES Address (Id);

-- Reference: BID_AUCTION (table: BID)
ALTER TABLE BID ADD CONSTRAINT BID_AUCTION
    FOREIGN KEY (AuctionId)
    REFERENCES AUCTION (Id);

-- Reference: BID_CUSTOMER (table: BID)
ALTER TABLE BID ADD CONSTRAINT BID_CUSTOMER
    FOREIGN KEY (CustomerId)
    REFERENCES CUSTOMER (Id);

-- Reference: CUSTOMER_AUCTION (table: AUCTION)
ALTER TABLE AUCTION ADD CONSTRAINT CUSTOMER_AUCTION
    FOREIGN KEY (WinnerId)
    REFERENCES CUSTOMER (Id);

-- Reference: EMPLOYEE_AUCTION (table: AUCTION)
ALTER TABLE AUCTION ADD CONSTRAINT EMPLOYEE_AUCTION
    FOREIGN KEY (EmployeeId)
    REFERENCES EMPLOYEE (Id);

-- Reference: EMPLOYEE_DEALERSHIP (table: EMPLOYEE)
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_DEALERSHIP
    FOREIGN KEY (DealershipId)
    REFERENCES DEALERSHIP (Id);

-- Reference: FEEDBACK_CUSTOMER (table: FEEDBACK)
ALTER TABLE FEEDBACK ADD CONSTRAINT FEEDBACK_CUSTOMER
    FOREIGN KEY (CustomerId)
    REFERENCES CUSTOMER (Id);

-- Reference: FEEDBACK_SELLER (table: FEEDBACK)
ALTER TABLE FEEDBACK ADD CONSTRAINT FEEDBACK_SELLER
    FOREIGN KEY (EmployeeId)
    REFERENCES EMPLOYEE (Id);

-- Reference: INVOICE_CUSTOMER (table: INVOICE)
ALTER TABLE INVOICE ADD CONSTRAINT INVOICE_CUSTOMER
    FOREIGN KEY (CustomerId)
    REFERENCES CUSTOMER (Id);

-- Reference: INVOICE_ITEM_INVOICE (table: INVOICE_ITEM)
ALTER TABLE INVOICE_ITEM ADD CONSTRAINT INVOICE_ITEM_INVOICE
    FOREIGN KEY (InvoiceId)
    REFERENCES INVOICE (Id);

-- Reference: INVOICE_ITEM_VEHICLE (table: INVOICE_ITEM)
ALTER TABLE INVOICE_ITEM ADD CONSTRAINT INVOICE_ITEM_VEHICLE
    FOREIGN KEY (VehicleId)
    REFERENCES VEHICLE (Id);

-- Reference: INVOICE_SELLER (table: INVOICE)
ALTER TABLE INVOICE ADD CONSTRAINT INVOICE_SELLER
    FOREIGN KEY (EmployeeId)
    REFERENCES EMPLOYEE (Id);

-- Reference: VEHICLE_AUCTION (table: AUCTION)
ALTER TABLE AUCTION ADD CONSTRAINT VEHICLE_AUCTION
    FOREIGN KEY (VehicleId)
    REFERENCES VEHICLE (Id);

-- Reference: VEHICLE_Parking (table: VEHICLE)
ALTER TABLE VEHICLE ADD CONSTRAINT VEHICLE_Parking
    FOREIGN KEY (ParkingId)
    REFERENCES Parking (Id);

-- sequences
-- Sequence: INVOICE_ITEM_seq
CREATE SEQUENCE INVOICE_ITEM_seq
      INCREMENT BY 1
      NOMINVALUE
      NOMAXVALUE
      START WITH 1
      NOCACHE
      NOCYCLE;

-- End of file.

