CREATE OR REPLACE TYPE polskafaktura AS OBJECT
(
    DATA       DATE,
    KWOTANETTO DECIMAL,
    CONSTRUCTOR FUNCTION POLSKAFAKTURA(DATA DATE) RETURN SELF AS RESULT,
    CONSTRUCTOR FUNCTION POLSKAFAKTURA(DATA DATE, KWOTANETTO DECIMAL) RETURN SELF AS RESULT,
    MEMBER FUNCTION STAWKAVAT RETURN INT,
    MEMBER FUNCTION WYLICZBRUTTO RETURN DECIMAL,
    MEMBER PROCEDURE DRUKUJ
) instantiable not final;

CREATE OR REPLACE TYPE BODY polskafaktura AS
    CONSTRUCTOR FUNCTION POLSKAFAKTURA(DATA DATE) RETURN SELF AS RESULT IS
    BEGIN
        SELF.DATA := DATA;
        RETURN;
    END;
    CONSTRUCTOR FUNCTION POLSKAFAKTURA(DATA DATE, KWOTANETTO DECIMAL) RETURN SELF AS RESULT IS
    BEGIN
        SELF.DATA := DATA;
        SELF.KWOTANETTO := KWOTANETTO;
        RETURN;
    END;
    MEMBER FUNCTION STAWKAVAT RETURN INT IS
    BEGIN
        RETURN 23;
    END;
    MEMBER FUNCTION WYLICZBRUTTO RETURN DECIMAL IS
    BEGIN
        RETURN KWOTANETTO;
    END;
    MEMBER PROCEDURE DRUKUJ IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE(SELF.DATA ||
                             ' Faktura PL ' ||
                             SELF.KWOTANETTO ||
                             ' ' ||
                             'Stawka VAT: ' ||
                             SELF.STAWKAVAT ||
                             SELF.WYLICZBRUTTO);
    END;
END;

CREATE OR REPLACE TYPE niemieckafaktura UNDER polskafaktura
(
    OVERRIDING MEMBER FUNCTION STAWKAVAT RETURN INT,
    OVERRIDING MEMBER PROCEDURE DRUKUJ
) instantiable not final;

CREATE OR REPLACE TYPE BODY niemieckafaktura AS
    OVERRIDING MEMBER FUNCTION STAWKAVAT RETURN INT IS
    BEGIN
        RETURN 19;
    END;
    OVERRIDING MEMBER PROCEDURE DRUKUJ IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE(SELF.DATA || ' Faktura DE ' || SELF.KWOTANETTO || ' ' || 'Stawka VAT: ' ||
                             SELF.STAWKAVAT ||
                             SELF.WYLICZBRUTTO);
    END;
END;

DECLARE
    f1 polskafaktura;
    f2 niemieckafaktura;
BEGIN
    f1 := polskafaktura(SYSDATE, 100);
    f1.DRUKUJ();
    f2 := niemieckafaktura(SYSDATE, 100);
    f2.DRUKUJ();
END;
