CREATE OR REPLACE TYPE faktura AS OBJECT
(
    DATA       DATE,
    KWOTANETTO DECIMAL,
    CONSTRUCTOR FUNCTION FAKTURA(DATA DATE) RETURN SELF AS RESULT,
    CONSTRUCTOR FUNCTION FAKTURA(DATA DATE, KWOTANETTO DECIMAL) RETURN SELF AS RESULT,
    MEMBER FUNCTION WYLICZBRUTTO(VAT INT) RETURN DECIMAL,
    MEMBER PROCEDURE DRUKUJ
);

CREATE OR REPLACE TYPE BODY faktura AS
    CONSTRUCTOR FUNCTION FAKTURA(DATA DATE) RETURN SELF AS RESULT IS
    BEGIN
        SELF.DATA := DATA; RETURN;
    END;
    CONSTRUCTOR FUNCTION FAKTURA(DATA DATE, KWOTANETTO DECIMAL) RETURN SELF AS RESULT IS
    BEGIN
        SELF.DATA := DATA; SELF.KWOTANETTO := KWOTANETTO; RETURN;
    END;
    MEMBER FUNCTION WYLICZBRUTTO(VAT INT) RETURN DECIMAL IS
    BEGIN
        RETURN SELF.KWOTANETTO * VAT;
    END;
    MEMBER PROCEDURE DRUKUJ IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE(DATA || ' ' || KWOTANETTO || ' ' || WYLICZBRUTTO(23));
    END;
END;

DECLARE
    f1 faktura;
BEGIN
    f1 := faktura(SYSDATE, 100);
    f1.DRUKUJ();
END;
