SET DEFINE OFF

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (1, '3', 221, 792);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (2, '8', 193, 735);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (3, '8', 57, 186);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (4, '10', 429, 521);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (5, '5', 198, 99);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (6, '1', 157, 975);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (7, '6', 263, 314);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (8, '8', 129, 35);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (9, '6', 474, 218);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (10, '2', 421, 484);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (11, '5', 302, 881);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (12, '8', 468, 965);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (13, '2', 389, 284);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (14, '6', 30, 872);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (15, '8', 4, 699);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (16, '4', 497, 293);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (17, '9', 346, 579);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (18, '8', 471, 933);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (19, '5', 186, 606);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (20, '8', 272, 196);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (21, '7', 401, 214);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (22, '9', 156, 520);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (23, '2', 11, 453);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (24, '6', 123, 620);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (25, '8', 227, 506);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (26, '8', 40, 693);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (27, '1', 366, 689);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (28, '4', 305, 451);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (29, '3', 303, 607);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (30, '2', 248, 538);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (31, '6', 243, 604);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (32, '6', 258, 825);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (33, '6', 140, 750);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (34, '7', 446, 402);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (35, '1', 106, 751);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (36, '10', 359, 744);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (37, '7', 406, 926);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (38, '1', 345, 682);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (39, '8', 188, 335);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (40, '10', 246, 147);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (41, '3', 183, 704);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (42, '10', 324, 443);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (43, '9', 233, 104);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (44, '9', 76, 156);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (45, '1', 53, 950);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (46, '7', 330, 322);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (47, '6', 296, 82);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (48, '3', 296, 438);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (49, '6', 304, 684);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (50, '5', 146, 444);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (51, '8', 126, 881);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (52, '8', 265, 402);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (53, '6', 483, 32);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (54, '6', 418, 523);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (55, '9', 271, 475);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (56, '10', 155, 357);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (57, '8', 438, 859);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (58, '2', 290, 630);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (59, '6', 385, 111);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (60, '8', 199, 109);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (61, '1', 118, 163);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (62, '6', 368, 783);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (63, '10', 341, 980);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (64, '2', 396, 94);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (65, '4', 481, 408);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (66, '1', 346, 496);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (67, '10', 167, 531);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (68, '7', 245, 606);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (69, '6', 209, 132);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (70, '4', 207, 780);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (71, '2', 73, 413);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (72, '1', 27, 63);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (73, '1', 409, 138);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (74, '4', 163, 57);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (75, '5', 129, 344);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (76, '7', 422, 317);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (77, '1', 369, 912);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (78, '7', 169, 794);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (79, '3', 231, 81);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (80, '1', 315, 808);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (81, '2', 221, 988);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (82, '3', 83, 367);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (83, '2', 87, 846);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (84, '3', 65, 545);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (85, '5', 315, 906);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (86, '8', 334, 353);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (87, '7', 171, 701);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (88, '3', 170, 580);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (89, '1', 95, 86);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (90, '4', 397, 526);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (91, '10', 376, 686);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (92, '2', 95, 371);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (93, '1', 57, 81);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (94, '7', 355, 841);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (95, '7', 347, 524);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (96, '1', 495, 836);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (97, '2', 150, 141);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (98, '5', 166, 383);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (99, '5', 176, 455);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (100, '1', 76, 126);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (101, '2', 378, 495);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (102, '1', 175, 281);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (103, '3', 136, 873);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (104, '6', 382, 109);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (105, '4', 215, 44);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (106, '9', 336, 105);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (107, '7', 301, 516);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (108, '1', 130, 801);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (109, '6', 49, 667);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (110, '8', 418, 16);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (111, '1', 192, 491);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (112, '4', 156, 679);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (113, '2', 109, 266);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (114, '8', 316, 979);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (115, '6', 297, 645);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (116, '8', 187, 933);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (117, '2', 110, 636);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (118, '1', 129, 235);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (119, '7', 204, 568);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (120, '3', 70, 754);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (121, '9', 163, 733);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (122, '8', 363, 562);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (123, '9', 29, 825);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (124, '10', 64, 374);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (125, '6', 36, 304);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (126, '2', 290, 583);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (127, '10', 324, 84);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (128, '10', 263, 939);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (129, '3', 208, 749);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (130, '8', 88, 882);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (131, '7', 109, 201);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (132, '5', 147, 50);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (133, '8', 340, 193);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (134, '7', 241, 320);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (135, '5', 200, 413);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (136, '8', 447, 37);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (137, '5', 331, 707);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (138, '5', 488, 96);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (139, '7', 416, 816);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (140, '2', 186, 279);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (141, '4', 152, 576);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (142, '3', 46, 833);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (143, '3', 76, 791);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (144, '4', 426, 684);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (145, '5', 356, 669);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (146, '6', 283, 985);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (147, '10', 137, 628);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (148, '9', 337, 684);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (149, '8', 412, 769);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (150, '5', 326, 443);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (151, '10', 131, 677);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (152, '7', 74, 491);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (153, '3', 124, 257);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (154, '1', 469, 327);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (155, '6', 472, 792);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (156, '5', 156, 541);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (157, '9', 161, 84);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (158, '9', 496, 579);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (159, '8', 282, 225);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (160, '3', 448, 961);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (161, '10', 132, 562);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (162, '2', 48, 227);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (163, '6', 422, 593);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (164, '7', 423, 729);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (165, '9', 469, 661);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (166, '6', 378, 379);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (167, '9', 96, 414);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (168, '2', 181, 579);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (169, '1', 463, 55);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (170, '3', 426, 734);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (171, '6', 140, 514);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (172, '7', 168, 558);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (173, '5', 479, 269);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (174, '1', 242, 163);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (175, '7', 462, 143);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (176, '6', 483, 510);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (177, '8', 148, 745);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (178, '8', 359, 42);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (179, '6', 367, 390);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (180, '4', 55, 250);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (181, '9', 223, 130);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (182, '9', 441, 373);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (183, '8', 389, 638);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (184, '9', 432, 201);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (185, '10', 163, 997);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (186, '4', 75, 154);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (187, '10', 385, 873);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (188, '5', 418, 765);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (189, '8', 367, 90);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (190, '6', 407, 912);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (191, '3', 196, 606);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (192, '9', 229, 867);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (193, '6', 60, 178);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (194, '6', 12, 834);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (195, '3', 417, 95);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (196, '1', 212, 316);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (197, '10', 398, 515);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (198, '9', 199, 820);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (199, '1', 22, 800);

INSERT INTO FEEDBACK (ID, DESCRIPTION, EMPLOYEEID, CUSTOMERID) 
VALUES (200, '9', 306, 613);

-- Import Data into table FEEDBACK from file C:\Users\Piotr\Downloads\MOCK_DATA (12).csv . Task successful and sent to worksheet.
