CREATE TABLE Auction(
    auction_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    expiry TIMESTAMP, 
    vehicleID number,
    winnerID NUMBER,
    employeeID NUMBER,
    PRIMARY KEY(auction_id)
);

CREATE TABLE Parking(
    ParkingID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    DealershipID NUMBER,
    PRIMARY KEY(ParkingID)
);

CREATE TABLE Vehicle(
    vehicleID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name varchar2(50),
    manufacturerDate DATE,
    manufacturer varchar2(50),
    countryOfOrigin varchar2(50),
    ownersCount number,
    parkingID number REFERENCES Parking(ParkingID),
    PRIMARY KEY(vehicleID)
);

CREATE TABLE Address(
    addressID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    street varchar2(50),
    streetNumber number,
    city varchar2(50),
    postCode varchar2(50),
    country varchar2(50),
    PRIMARY KEY(addressID)
);

CREATE TABLE dealership(
    dealershipID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    addressID REFERENCES address(addressID)
);

